RiversideHealth/Models/HealthTips.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RiversideHealth.Models
{
    public class HealthTips
    {
        [Key]
        public int TipsId { get; set; }

        [Required, StringLength(50), Display(Name = "Tips Title")]
        public string TipsTitle { get; set; }

        [Required, StringLength(255), Display(Name = "Tips Description")]
        public string TipsDescription { get; set; }

        public int TipStatus { get; set; }

        [ForeignKey("TipsCategoryId")]
        public int TipsCategoryId { get; set; }

        public virtual HealthTipsCategory HealthTipsCategory { get; set; }

    }
}

RiversideHealth/Controllers/HealthTipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using RiversideHealth.Models;
using RiversideHealth.Models.ViewModels;
using RiversideHealth.Data;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

namespace RiversideHealth.Controllers
{
    public class HealthTipsController : Controller
    {
        private readonly RiversideHealthDbContext context;
        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public HealthTipsController(RiversideHealthDbContext ctx, UserManager<ApplicationUser> userManager)
        {
            context = ctx;
            _userManager = userManager;
        }

        public async Task<ActionResult> Index(int page)
        {
            var admin = await GetCurrentUserAsync();
            if (admin != null)
            {
                if (admin.AdminId == null)
                {
                    ViewData["UserIsAdmin"] = "False";
                }
                else
                {
                    ViewData["UserIsAdmin"] = admin.AdminId.ToString();
                }
            }
            else
            {
                ViewData["UserIsAdmin"] = "False";
            }

            var myCategories = await context.HealthTips.ToListAsync();
            int pagecount = myCategories.Count();
            int pageItems = 8;
            int limit = (int)Math.Ceiling((decimal)pagecount / pageItems) - 1;

            limit = limit < 0 ? 0 : limit;
            page = page < 0 ? 0 : page;
            page = page > limit ? limit : page;

            int initial = pageItems * page;

            ViewData["page"] = (int)page;
            ViewData["PageSummary"] = "";

            if (limit > 0)
            {
                ViewData["PageSummary"] =
                    (page + 1).ToString() + " of " +
                    (limit + 1).ToString();
            }

            List<HealthTips> ht = await context.HealthTips.Skip(initial).Take(pageItems).ToListAsync();

            //return the view
            return View(ht);
        }

        public async Task<ActionResult> Create()
        {
            var admin = await GetCurrentUserAsync();
            if (admin != null)
            {
                if (admin.AdminId == null)
                {
                    ViewData["UserIsAdmin"] = "False";
                    // redirect if user isnt logged in
                    //return Redirect("/Account/Login");
                }
                else
                {
                    ViewData["UserIsAdmin"] = admin.AdminId.ToString();
                }
            }
            else
            {
                ViewData["UserIsAdmin"] = "False";
                // redirect if user isnt logged in
                //return Redirect("/Account/Login");
            }

            HealthtipEdit he = new HealthtipEdit();
            //assign contents
            he.HealthTipsCategory = context.HealthTipsCategories.ToList();

            // pass the view model into the view
            return View(he);
        }

        [HttpPost]
        public ActionResult Create(string tipsTitle, string tipsDescription, int tipsStatus, int tipsCategoryId)
        {
            // create an entity and assign the values
            HealthTips ht = new HealthTips()
            {
                TipsTitle = tipsTitle,
                TipsDescription = tipsDescription,
                TipStatus = tipsStatus,
                TipsCategoryId = tipsCategoryId
            };

            //insert query
            context.HealthTips.Add(ht);

            //save
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int id)
        {
            var admin = await GetCurrentUserAsync();
            if (admin != null)
            {
                if (admin.AdminId == null)
                {
                    ViewData["UserIsAdmin"] = "False";
                    // redirect if user isnt logged in
                    //return Redirect("/Account/Login");
                }
                else
                {
                    ViewData["UserIsAdmin"] = admin.AdminId.ToString();
                }
            }
            else
            {
                ViewData["UserIsAdmin"] = "False";
                // redirect if user isnt logged in
                //return Redirect("/Account/Login");
            }

            HealthtipEdit he = new HealthtipEdit();
            //assign contents
            he.HealthTips = context.HealthTips.Find(id);
            he.HealthTipsCategory = context.HealthTipsCategories.ToList();

            // pass the view model to the view
            return View(he);
        }

        [HttpPost]
        public ActionResult Edit(int id, string tipsTitle_update, string tipsDescription_update, int tipsStatus_update, int tipsCategoryId_update)
        {
            // create new entity object
            HealthTips ht = new HealthTips()
            {
                TipsId = id
            };

            // attach the obect so we can edit it
            context.HealthTips.Attach(ht);

            // add the updates
            ht.TipsTitle = tipsTitle_update;
            ht.TipsDescription = tipsDescription_update;
            ht.TipStatus = tipsStatus_update;
            ht.TipsCategoryId = tipsCategoryId_update;

            // save to database
            context.SaveChanges();

            return Redirect("/HealthTips/Details/" + id);
        }

        public ActionResult Details(int id)
        {
            HealthtipEdit he = new HealthtipEdit();
            //assign contents
            he.HealthTips = context.HealthTips.Find(id);

            // include only the category of the health tip
            he.HealthTipsCategory = context.HealthTipsCategories.Where(htc => htc.TipsCategoryId == he.HealthTips.TipsCategoryId).ToList();

            // pass the view model
            return View(he);
        }

        public ActionResult Delete(int id)
        {
            // create new entity object
            // reference https://davidsekar.com/c-sharp/modify-or-delete-entity-object-without-select

            HealthTips ht = new HealthTips() { TipsId = id };

            // attach to entity
            context.HealthTips.Attach(ht);

            // remove the record
            context.HealthTips.Remove(ht);

            // save the changes
            context.SaveChanges();

            // redirect to index
            return RedirectToAction("Index");
        }
    }
}

RiversideHealth/Views/HealthTips/Create.cshtml
@model RiversideHealth.Models.ViewModels.HealthtipEdit

@{
    ViewData["Title"] = "Create";
}

<h2>Add HealthTips</h2>
<hr />
<form action="/HealthTips/Create" method="post">
    <div class="form-group">
        <label clas"control-label">Title</label>
        <input type="text" class="form-control" name="tipsTitle" />
    </div>
    <div class="form-group">
        <label clas"control-label">Description</label>
        <textarea class="form-control" name="tipsDescription"></textarea>
    </div>
    <div class="form-group">
        <label clas"control-label">Publish Status</label>
        <select name="tipsStatus" class="form-control">
            <option value="0">Unpublished</option>
            <option value="1">Published</option>
        </select>
    </div>    
    <div class="form-group">
        <label clas"control-label">Category</label>
        <select name="tipsCategoryId" class="form-control">
            @foreach (var cat in Model.HealthTipsCategory)
            {
                <option value="@cat.TipsCategoryId">@cat.CategoryTitle</option>
            }
        </select>
    </div>    
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Create" />
    </div>
</form>

RiversideHealth/Views/HealthTips/Details.cshtml
@model RiversideHealth.Models.ViewModels.HealthtipEdit

@{
    ViewData["Title"] = "Details";
}
@if ((string)ViewData["UserIsAdmin"] != "False")
{
    <div>
        <a href="/HealthTips/Edit/@Model.HealthTips.TipsId">Edit</a> |
        <a href="/HealthTips/Index">Back to List</a>
    </div>
}
<div>
    <h2>@Model.HealthTips.TipsTitle</h2>
    <p>
        Category:
        @foreach (var cat in Model.HealthTipsCategory)
        {
            @cat.CategoryTitle
        }
    </p>
    <hr />
    <div class="col-md-10">
        <p>@Model.HealthTips.TipsDescription</p>
    </div>
</div>

RiversideHealth/Views/HealthTips/Edit.cshtml
@model RiversideHealth.Models.ViewModels.HealthtipEdit

@{
    ViewData["Title"] = "Edit";
}

<div>
    <a href="/HealthTips/Index">Back to List</a>
</div>

<h2>Edit HealthTips</h2>
<hr />
<form action="/HealthTips/Edit/@Model.HealthTips.TipsId" method="post">
    <div class="form-group">
        <label clas"control-label">Title</label>
        <input type="text" class="form-control" name="tipsTitle_update" value="@Model.HealthTips.TipsTitle"/>
    </div>
    <div class="form-group">
        <label clas"control-label">Description</label>
        <textarea class="form-control" name="tipsDescription_update">@Model.HealthTips.TipsDescription</textarea>
    </div>
    <div class="form-group">
        <label clas"control-label">Publish Status</label>
        <select name="tipsStatus_update" class="form-control">
            @{
                string published = "";
                string unpublished = "";
                if (Model.HealthTips.TipStatus == 0)
                {
                    unpublished = "selected";
                }
                else
                {
                    published = "selected";
                }
            }
            <option value="0" selected="@unpublished">Unpublished</option>
            <option value="1" selected="@published">Published</option>
        </select>
    </div>
    <div class="form-group">
        <label clas"control-label">Category</label>
        <select name="tipsCategoryId_update" class="form-control">
            @foreach (var cat in Model.HealthTipsCategory)
            {
                string selected = "";
                if (Model.HealthTips.TipsCategoryId == cat.TipsCategoryId)
                {
                    selected = "selected";
                }

                // set selected if it matches the id
                <option value="@cat.TipsCategoryId" selected="@selected">@cat.CategoryTitle</option>
            }
        </select>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Update" />
    </div>
</form>

RiversideHealth/Views/HealthTips/Index.cshtml
@model IEnumerable<RiversideHealth.Models.HealthTips>
@{
    ViewData["Title"] = "Index";
}
<a href="/HealthTips/Create">Create New</a>
<h2>Health Tips</h2>
@if ((string)ViewData["UserIsAdmin"] == "False")
{
<div class="row">
    @foreach (var item in Model)
    {
        // if it's published
        if (item.TipStatus == 1)
        {
            <div class="col-sm-6 col-md-3">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>@item.TipsTitle</h3>
                        <p class="text-right"><a href="/HealthTips/Details/@item.TipsId" class="btn btn-primary" role="button">View</a></p>
                    </div>
                </div>
            </div>
        }
    }
</div>
}
else
{
    <a href="/HealthTips/Create">Create New</a>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Status
                </th>
                <th class="text-right">
                    Options
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.TipsTitle
                    </td>
                    <td>
                        @item.TipsDescription
                    </td>
                    <td>
                        @item.TipStatus
                    </td>
                    <td class="text-right">
                        <a href="/HealthTips/Edit/@item.TipsId" class="btn btn-link">Edit</a> |
                        <a href="/HealthTips/Details/@item.TipsId" class="btn btn-link">Details</a> |
                        <a href="/HealthTips/Delete/@item.TipsId" class="btn btn-link">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<!-- Pagination -->
    <div class="text-center">
        <!--html decode to add arrows
            reference: https://stackoverflow.com/questions/35437491/webutility-htmldecode-replacement-in-net-core
        -->
        @Html.ActionLink(System.Net.WebUtility.HtmlDecode("&larr; Prev"), "Index", "HealthTips", new { page = ((int)ViewData["page"] - 1) })
        @ViewData["PageSummary"]
        @Html.ActionLink(System.Net.WebUtility.HtmlDecode("Next &rarr;"), "Index", "HealthTips", new { page = ((int)ViewData["page"] + 1) })
    </div>