RiversideHealth/Models/FrequentlyAskedQuestions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace RiversideHealth.Models
{
    public class FrequentlyAskedQuestions
    {
        [Key]
        public int FaqID { get; set; }

        [Required, StringLength(int.MaxValue), Display(Name = "Question")]
        public string FaqQuestion { get; set; }

        [Required, StringLength(int.MaxValue), DataType(DataType.MultilineText), Display(Name = "Answer")]
        public string FaqAnswer { get; set; }

        //false for inactive, true for active.
        [Required, Display(Name = "Status")]
        public bool IsPublished { get; set; }

        [Required, DataType(DataType.DateTime), Display(Name = "Created On")]
        public DateTime DateCreated { get; set; }

        [ForeignKey("AdminId")]
        public int AdminId { get; set; }

        public virtual Admin Admin { get; set; }
    }
}

RiversideHealth/Controllers/FrequentlyAskedQuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using RiversideHealth.Models;
using RiversideHealth.Models.ViewModels;
using RiversideHealth.Data;
using Microsoft.AspNetCore.Http;

namespace RiversideHealth.Controllers
{
    public class FrequentlyAskedQuestionController : Controller
    {

        private readonly RiversideHealthDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public FrequentlyAskedQuestionController(RiversideHealthDbContext context, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _userManager = usermanager;
        }

        public IActionResult Index()
        {
            return View();
        }

        //User

        public async Task<ActionResult> FaqUserList(int pagenum)
        {
            var user = await GetCurrentUserAsync();

            if (user != null)
            {
                if (user.AdminId != null)
                {
                    return RedirectToAction("FaqAdminList");
                }
            }

            /*Pagination Algorithm*/
            var _faq = await db.FrequentlyAskedQuestions.Where(a=>a.IsPublished==true).ToListAsync();
            int pagecount = _faq.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)pagecount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }
            List<FrequentlyAskedQuestions> frequentlyAskedQuestions = await db.FrequentlyAskedQuestions.Where(a => a.IsPublished == true).Skip(start).Take(perpage).ToListAsync();
            /*End of Pagination  Algorithm*/

            return View(frequentlyAskedQuestions);

        }

        public ActionResult FaqUserDetail(int id)
        {
            //List<FrequentlyAskedQuestions> frequentlyAskedQuestions = await db.FrequentlyAskedQuestions.Where(a => a.FaqID ==id).ToListAsync();

            //return View(frequentlyAskedQuestions);

            return View(db.FrequentlyAskedQuestions.SingleOrDefault(p => p.FaqID == id));
        }
        
        //Admin  
        public async Task<ActionResult> FaqAdminList(int pagenum)
        {
            var user = await GetCurrentUserAsync();
        
            if (user != null)
            {
                if (user.AdminId == null) { ViewData["UserIsAdmin"] = "false"; }
                else { ViewData["UserIsAdmin"] = user.AdminId.ToString(); }
            }
            else
            {
                ViewData["UserIsAdmin"] = "false";
            }

            /*Pagination Algorithm*/
            var _faq = await db.FrequentlyAskedQuestions.Include(a => a.Admin).ToListAsync();
            int pagecount = _faq.Count();
            int perpage = 10;
            int maxpage = (int)Math.Ceiling((decimal)pagecount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }
            List<FrequentlyAskedQuestions> faq = await db.FrequentlyAskedQuestions.Include(a => a.Admin).Skip(start).Take(perpage).ToListAsync();
            /*End of Pagination  Algorithm*/

            return View(faq);
        }

        public async Task<ActionResult> FaqAdminCreate()
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminId == null) { ViewData["UserIsAdmin"] = "false"; }
                else { ViewData["UserIsAdmin"] = user.AdminId.ToString(); }
            }
            else
            {
                ViewData["UserIsAdmin"] = "false";
            }            
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> FaqAdminCreate(string FaqQuestion, string FaqAnswer, bool IsPublished)
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminId != null) {

                    string query = "insert into dbo.Faq (FaqQuestion, FaqAnswer, IsPublished, DateCreated, AdminId) values (@FaqQuestion, @FaqAnswer, @IsPublished, @DateCreated, @AdminId)";
                    SqlParameter[] myparams = new SqlParameter[9];
                    myparams[0] = new SqlParameter("@FaqQuestion", FaqQuestion);
                    myparams[1] = new SqlParameter("@FaqAnswer", FaqAnswer);
                    myparams[2] = new SqlParameter("@IsPublished", IsPublished);
                    myparams[3] = new SqlParameter("@DateCreated", DateTime.UtcNow);
                    myparams[5] = new SqlParameter("@AdminId", user.AdminId.ToString());

                    db.Database.ExecuteSqlCommand(query, myparams);
                    return RedirectToAction("FaqAdminList");
                }

            }        

            return RedirectToAction("FaqAdminList");
        }


        public async Task<ActionResult> FaqAdminEdit(int id)
        {
            //List<FrequentlyAskedQuestions> frequentlyAskedQuestions = await db.FrequentlyAskedQuestions.Where(a => a.FaqID ==id).ToListAsync();

            //return View(frequentlyAskedQuestions);


            //get current user details
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminId == null) { ViewData["UserIsAdmin"] = "false"; }
                else { ViewData["UserIsAdmin"] = user.AdminId.ToString(); }
                return View(db.FrequentlyAskedQuestions.SingleOrDefault(p => p.FaqID == id));
            }
            else
            {
                ViewData["UserIsAdmin"] = "false";
            }
            return RedirectToAction("FaqAdminList");
        }

        [HttpPost]
        public async Task<ActionResult> FaqAdminEdit(int FaqID, string FaqQuestion, string FaqAnswer, bool IsPublished)
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminId != null)
                {

                    string query = "UPDATE dbo.Faq SET FaqQuestion=@FaqQuestion, FaqAnswer=@FaqAnswer, IsPublished=@IsPublished,DateCreated = @DateCreated, AdminId=@AdminId WHERE FaqID=@FaqID";
                    SqlParameter[] myparams = new SqlParameter[9];
                    myparams[0] = new SqlParameter("@FaqQuestion", FaqQuestion);
                    myparams[1] = new SqlParameter("@FaqAnswer", FaqAnswer);
                    myparams[2] = new SqlParameter("@IsPublished", IsPublished);
                    myparams[3] = new SqlParameter("@DateCreated", DateTime.UtcNow);
                    myparams[4] = new SqlParameter("@AdminId", user.AdminId);
                    myparams[5] = new SqlParameter("@FaqID", FaqID);

                    db.Database.ExecuteSqlCommand(query, myparams);
                    return RedirectToAction("FaqAdminList");
                }

            }

            return RedirectToAction("FaqAdminList");
        }



    }
}

RiversideHealth/Views/FrequentlyAskedQuestion/FaqAdminCreate.cshtml
@model RiversideHealth.Models.FrequentlyAskedQuestions

@{
    ViewData["Title"] = "FaqAdminCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if ((string)ViewData["UserIsAdmin"] != "false")
{
    <h4>Add new Frequently Asked Questions</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="FaqAdminCreate">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FaqQuestion" class="control-label"></label>
                    <input asp-for="FaqQuestion" class="form-control" />
                    <span asp-validation-for="FaqQuestion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FaqAnswer" class="control-label"></label>
                    <input asp-for="FaqAnswer" class="form-control" />
                    <span asp-validation-for="FaqAnswer" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsPublished" /> Publish @*@Html.DisplayNameFor(model => model.IsPublished)*@
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="FaqAdminList">Back to List</a>
    </div>
}
else
{
    <div class="row">
        <div class="col-lg-4 col-md-4" id="unauthorizedaccesserrorimg">
        </div>
        <div class="col-lg-5 col-md-5">
            <img src="~/images/Unauthorized-Access-error.png" alt="Unauthorized access" />
        </div>
        <div class="col-lg-3 col-md-3">

        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4" id="unauthorizedaccesserrorimg">
        </div>
        <div class="col-lg-5 col-md-5">
            <h3 style="color: red;">You are not authroized to access this page.Try again with valid credentials.</h3>

        </div>
        <div class="col-lg-3 col-md-3">

        </div>
    </div>
}

RiversideHealth/Views/FrequentlyAskedQuestion/FaqAdminEdit.cshtml
@model RiversideHealth.Models.FrequentlyAskedQuestions

@{
    ViewData["Title"] = "FaqAdminEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if ((string)ViewData["UserIsAdmin"] != "false")
{
    <h4>FrequentlyAskedQuestions</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="FaqAdminEdit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="FaqID" />
                <div class="form-group">
                    <label asp-for="FaqQuestion" class="control-label"></label>
                    <input asp-for="FaqQuestion" class="form-control" />
                    <span asp-validation-for="FaqQuestion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FaqAnswer" class="control-label"></label>
                    @Html.TextAreaFor(model => model.FaqAnswer, new { htmlAttributes = new { @class = "form-control" }, cols = 35, @rows = 3 })
                    @*  <input asp-for="FaqAnswer" class="form-control" />*@
                    <span asp-validation-for="FaqAnswer" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsPublished" /> Publish @*@Html.DisplayNameFor(model => model.IsPublished)*@
                        </label>
                    </div>
                </div>
                @*<div >
                    <input type="hidden" value="@ViewData['UserIsAdmin'].ToString()" id="AdminId" name="AdminId"/>
                </div>*@

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="FaqAdminList">Back to List</a>
    </div>
}
else
{
    <div class="row">
        <div class="col-lg-4 col-md-4" id="unauthorizedaccesserrorimg">
        </div>
        <div class="col-lg-5 col-md-5">
            <img src="~/images/Unauthorized-Access-error.png" alt="Unauthorized access" />
        </div>
        <div class="col-lg-3 col-md-3">

        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4" id="unauthorizedaccesserrorimg">
        </div>
        <div class="col-lg-5 col-md-5">
            <h3 style="color: red;">You are not authroized to access this page.Try again with valid credentials.</h3>

        </div>
        <div class="col-lg-3 col-md-3">

        </div>
    </div>
}

RiversideHealth/Views/FrequentlyAskedQuestion/FaqAdminList.cshtml
@model IEnumerable<RiversideHealth.Models.FrequentlyAskedQuestions>

@{
    ViewData["Title"] = "Frequently Asked Questions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="recadd">
    @if ((string)ViewData["UserIsAdmin"] != "false")
    {
        <div class="banner" id="faqbanner">
            <h2>Manage FAQ</h2>
        </div>
        @Html.ActionLink("Add new FAQ", "FaqAdminCreate")

        <table class="table">
            <tr>
                <th class="faqadminlistques">
                    Question
                </th>
                <th>
                    Answer
                </th>
                <th class="faqadminlistdate">
                    Date Created
                </th>
                <th>
                    Status
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FaqQuestion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FaqAnswer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreated)
                    </td>
                    <td>
                        @if (item.IsPublished)
                        {
                            <span class="text-success">@Html.Raw("Active")</span>
                        }
                        else
                        {
                            <span class="text-danger">@Html.Raw("Inactive")</span>
                        }
                    </td>
                    <td>
                        <a href="@Url.Action("FaqAdminEdit", "FrequentlyAskedQuestion", new { id = item.FaqID })">Edit</a>
                        @*<a href="@Url.Action("FaqAdminDelete", "SuperAdmin", new { id = item.FaqID })">Delete</a>*@
                    </td>
                </tr>
            }

        </table>

        <div>
            @ViewData["PaginationSummary"]
            @Html.ActionLink("Prev",
                "FaqAdminList",
                "FrequentlyAskedQuestion",
                new { pagenum = ((int)ViewData["pagenum"] - 1) }
                )
            |
            @Html.ActionLink("Next",
                "FaqAdminList",
                "FrequentlyAskedQuestion",
                new { pagenum = ((int)ViewData["pagenum"] + 1) }
            )
        </div>
    }

    else
    {
        <div class="row">
            <div class="col-lg-4 col-md-4" id="unauthorizedaccesserrorimg">
            </div>
            <div class="col-lg-5 col-md-5">
                <img src="~/images/Unauthorized-Access-error.png" alt="Unauthorized access" />
            </div>
            <div class="col-lg-3 col-md-3">

            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-4" id="unauthorizedaccesserrorimg">
            </div>
            <div class="col-lg-5 col-md-5">
                <h3 style="color: red;">You are not authroized to access this page.Try again with valid credentials.</h3>

            </div>
            <div class="col-lg-3 col-md-3">

            </div>
        </div>
    }
</div>

RiversideHealth/Views/FrequentlyAskedQuestion/FaqUserDetail.cshtml
@model RiversideHealth.Models.FrequentlyAskedQuestions

@{
    ViewData["Title"] = "FaqUserDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>  

    <div class="faqquestion">
        @Html.DisplayFor(model => model.FaqQuestion)
    </div>

    <div class="faqanswer">
        @Html.DisplayFor(model => model.FaqAnswer)
    </div>

    @*<dl class="dl-horizontal">
            @*<dt>
                 @Html.DisplayNameFor(model => model.FaqQuestion)
            </dt>
            <dd>
                 @Html.DisplayFor(model => model.FaqQuestion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FaqAnswer)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FaqAnswer)
            </dd>
        </dl>*@
</div>
<div>
    <a asp-action="FaqUserList">Back to List</a>
</div>

RiversideHealth/Views/FrequentlyAskedQuestion/FaqUserList.cshtml
@model IEnumerable<RiversideHealth.Models.FrequentlyAskedQuestions>

@{
    ViewData["Title"] = "Frequently Asked Questions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="banner" id="careerbanner">
    <h2>Frequently Asked Questions</h2>
</div>
<div id="debugDiv">
</div>
@*<table class="table">
        <tr>
            <th>
                Question
            </th>
            <th>
                Answer
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <div class="faqquestion">
                        @Html.DisplayFor(modelItem => item.FaqQuestion)
                    </div>
                </td>
                <td>
                    <div class="faqanswer">

                        @Html.DisplayFor(modelItem => item.FaqAnswer)

                        @Html.ActionLink("Details", "FaqUserDetail", new { id = item.FaqID })
                    </div>
                </td>

            </tr>
        }

    </table>*@

@foreach (var item in Model)
    {
        <div class="faqquestion">
            @Html.DisplayFor(modelItem => item.FaqQuestion)
         </div>
   
        <div class="faqanswer">
            <span class="img-caption">@item.FaqAnswer.Substring(0,400)...</span>
            @*@Html.DisplayFor(modelItem => item.FaqAnswer)*@

            @Html.ActionLink("Details", "FaqUserDetail", new { id = item.FaqID })
        </div>
    }

<div>
    @ViewData["PaginationSummary"]
    @Html.ActionLink("Prev",
        "FaqUserList",
        "FrequentlyAskedQuestion",
        new { pagenum = ((int)ViewData["pagenum"] - 1) }
        )
    |
    @Html.ActionLink("Next",
        "FaqUserList",
        "FrequentlyAskedQuestion",
        new { pagenum = ((int)ViewData["pagenum"] + 1) }
    )
</div>