RiversideHealth/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using RiversideHealth.Models;
using RiversideHealth.Models.ViewModels;
using RiversideHealth.Data;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

namespace RiversideHealth.Controllers
{
    public class TransactionController : Controller
    {
        private readonly RiversideHealthDbContext context;
        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public TransactionController(RiversideHealthDbContext ctx, UserManager<ApplicationUser> userManager)
        {
            context = ctx;
            _userManager = userManager;
        }

        public async Task<ActionResult> Index(int page)
        {
            var admin = await GetCurrentUserAsync();
            if (admin != null)
            {
                if (admin.AdminId == null)
                {
                    ViewData["UserIsAdmin"] = "False";
                    // redirect if user isnt logged in
                   // return Redirect("/Account/Login");
                }
                else
                {
                    ViewData["UserIsAdmin"] = admin.AdminId.ToString();
                }
            }
            else
            {
                ViewData["UserIsAdmin"] = "False";
                // redirect if user isnt logged in
               // return Redirect("/Account/Login");
            }

            /*Pagination Algorithm*/
            // I based this on christine's code
            var myCategories = await context.Transactions.ToListAsync();
            int pagecount = myCategories.Count();
            int pageItems = 8;
            int limit = (int)Math.Ceiling((decimal)pagecount / pageItems) - 1;

            limit = limit < 0 ? 0 : limit;
            page = page < 0 ? 0 : page;
            page = page > limit ? limit : page;

            int initial = pageItems * page;

            ViewData["page"] = (int)page;
            ViewData["PageSummary"] = "";

            if (limit > 0)
            {
                ViewData["PageSummary"] =
                    (page + 1).ToString() + " of " +
                    (limit + 1).ToString();
            }

            List<Transaction> transactionList = await context.Transactions.Skip(initial).Take(pageItems).ToListAsync();
            return View(transactionList);
        }

        public ActionResult Details(int id)
        {
            return View(context.Transactions.Find(id));
        }
    }
}

RiversideHealth/Views/Transaction/Details.cshtml
@model RiversideHealth.Models.Transaction
@{
    ViewData["Title"] = "Details";
}

<h2>Transaction Details</h2>
<table class="table">
    <tr>
        <th>Reference ID</th>
        <th>Transaction Date</th>
        <th>Transaction Amount</th>
        <th>Transaction Status</th>
        <th>Donator</th>
    </tr>
    <tr>
        <td>@Model.ReferenceId</td>
        <td>@Model.TransactionDate</td>
        <td>$ @Model.TransactionAmount</td>
        <td>@Model.TransactionStatus</td>
        <td>@Model.DonatorId</td>
    </tr>

</table>

RiversideHealth/Views/Transaction/Index.cshtml
@model IEnumerable<RiversideHealth.Models.Transaction>
@{
    ViewData["Title"] = "Index";
}

<h2>Transaction List</h2>
<table class="table">
    <tr>
        <th>Reference ID</th>
        <th>Transaction Date</th>
        <th>Transaction Amount</th>
        <th>Transaction Status</th>
        <th>Donator</th>
        <th>Option</th>
    </tr>
    @foreach (var transactions in Model)
    {
        <tr>
            <td>@transactions.ReferenceId</td>
            <td>@transactions.TransactionDate</td>
            <td>$ @transactions.TransactionAmount</td>
            <td>@transactions.TransactionStatus</td>
            <td>@transactions.DonatorId</td>
            <td><a href="/Transaction/Details/@transactions.TransactionId">@transactions.DonatorId</td>
        </tr>
    }
</table>

<!-- Pagination -->
<div class="text-center">
    <!--html decode to add arrows
        reference: https://stackoverflow.com/questions/35437491/webutility-htmldecode-replacement-in-net-core
    -->
    @Html.ActionLink(System.Net.WebUtility.HtmlDecode("&larr; Prev"), "Index", "Transaction", new { page = ((int)ViewData["page"] - 1) })
    @ViewData["PageSummary"]
    @Html.ActionLink(System.Net.WebUtility.HtmlDecode("Next &rarr;"), "Index", "Transaction", new { page = ((int)ViewData["page"] + 1) })
</div>